name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  ci:
    strategy:
      matrix:
        platform:
          - [ubuntu-latest, x86_64-unknown-linux-gnu]
          - [macos-latest, aarch64-apple-darwin]
          - [windows-latest, x86_64-pc-windows-gnu]
    runs-on: ${{ matrix.platform[0] }}

    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - uses: dtolnay/rust-toolchain@1.89.0
        with:
              targets: ${{ matrix.platform[1] }}

      - name: Zig version
        run: zig version

      - name: Build & Test
        run: zig build test --summary all

      - name: Run integration tests
        run: |
          cd example
          zig build test --summary all
          cd ..
