name: Zig 0.12.0

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  ci:
    strategy:
      matrix:
        zig_verion: [0.12.0, master]
        platform: [ubuntu, macos, windows]
    runs-on: ${{ matrix.platform }}-latest

    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig_version }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform }}

      - name: Zig version
        run: zig version

      - name: Build
        run: zig build --summary all

      - name: Run integration tests
        run: |
          cd example
          zig build test --summary all
          cd ..
