name: Zig 0.12.0

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  ci:
    strategy:
      matrix:
        zig-verion: [0.12.0]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@2a9625d
        with:
          version: ${{ matrix.zig-version }}
          cache: false
      - uses: dtolnay/rust-toolchain@stable

      - name: Zig version
        run: zig version

      - name: Build
        run: zig build --summary all

      - name: Run integration tests
        run: |
          cd example
          zig build test --summary all
          cd ..
