name: Cross compilation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  cross-matrix:
    strategy:
      matrix:
        host: [ubuntu-latest, macos-latest, windows-latest]
        target:
          - [x86_64-linux,   x86_64-unknown-linux-musl, ubuntu-latest]
          - [aarch64-macos,      aarch64-apple-darwin,     macos-latest]
          - [x86_64-windows-gnu, x86_64-pc-windows-gnu,    windows-latest]

    uses: ./.github/workflows/cross-comp-reuse.yml
    with:
      host: ${{ matrix.host }}
      target: ${{ matrix.target[0] }}
      target-rust: ${{ matrix.target[1] }}
      target-runner: ${{ matrix.target[2] }}

  cross-comp-success:
    needs: [cross-matrix]
    runs-on: [ubuntu-latest]
    steps:
      - name: Success
        run: echo 'Success'
